version: "3"

networks:
  nginx-proxy-manager_default:
    external: true

services:
  parchment:
    image: httpd:latest
    container_name: parchment
    restart: always
    networks:
      - nginx-proxy-manager_default
    ports:
      - "8580:80"
    volumes:
      - /opt/medusa/parchment/project/build/html:/usr/local/apache2/htdocs/

