version: "3"

networks:
  nginx-proxy-manager_default:
    external: true

services:
  parchment:
    image: httpd:latest
    container_name: parchment
    environment:
      - APP_HOSTNAME=0.0.0.0
      - APP_PORT=80
    restart: always
    networks:
      - nginx-proxy-manager_default
    volumes:
      - ./build/html:/usr/local/apache2/htdocs/
    ports:
      - "8000:80"

