version: "3"

networks:
  nginx-proxy-manager:
    external: true

services:
  parchment:
    image: localhost/parchment:latest
    container_name: parchment
    restart: always
    networks:
      nginx-proxy-manager:
        ipv4_address: 172.18.2.4
    ports:
      - "41100:80"
    volumes:
      - /opt/medusa/parchment/project/build/html:/usr/local/apache2/htdocs/

