version: "3"

networks:
  nginx-proxy-manager:
    external: true

services:
  parchment:
    image: parchment
    container_name: parchment
    restart: always
    networks:
      nginx-proxy-manager:
        ipv4_address: 172.18.2.4
    ports:
      - "41000:80"
    volumes:
      - ./build/html:/usr/share/nginx/html

